import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const poppins = Poppins({ weight: "300" });

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className=" background relative h-screen w-screen  shadow-sm shadow-primary-20  sm:h-[93vh] sm:rounded-2xl sm:max-xl:w-[85vw] xl:max-w-[70em]">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
